"""user Calendly / scheduling link

Revision ID: 20260506_0039
Revises: 20260504_0038
Create Date: 2026-05-06 10:00:00

Stores the user's Calendly link (or similar scheduling URL) so that cold emails
generated by Henry can include a scheduling link when it's contextually relevant.

The link is optional and stored as-is without validation.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "20260506_0039"
down_revision = "20260504_0038"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column(
            "calendly_url",
            sa.String(length=500),
            nullable=True,
        ),
    )


def downgrade() -> None:
    op.drop_column("users", "calendly_url")
